---

- hosts: all
  become: true
  tasks:

  - name: install apache2 php and update cache package
    apt:
      name:
       -  apache2
       -  libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian","Ubuntu"]
     
