---

- hosts: all
  become: true
  tasks:

  - name: install apache and php for ubuntu server
    apt:
      name:
        - apache2
        - libpackage2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


  - name: install apache and php for centoz server
    dnf:
      name: 
        - http
        - phd 
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
